---

- name: check if nvme module loaded
  lineinfile:
    dest: /proc/modules
    regex: '^nvme*'
    state: absent
  check_mode: yes # without changes
  register: presence

- name: proceed if nvme module is present
  import_tasks: 'configure_mapping.yml'
  when: presence.changed or force_run | bool

...
